name: Update Top Langs

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Top Languages
        run: |
          mkdir -p assets
          curl -L -H "Accept: image/svg+xml" \
          "https://github-readme-stats.vercel.app/api/top-langs/?username=${{ github.repository_owner }}&layout=compact&theme=tokyonight" \
          -o assets/top-langs.svg

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add assets/top-langs.svg
          git commit -m "update top langs" || echo "no changes"
          git push
